# Get all comments by postId
GET http://localhost:3000/api/post/edea23ac-292a-4cea-ac69-658e08262082/comments HTTP/1.1

###

# Create new comment
POST http://localhost:3000/api/post/edea23ac-292a-4cea-ac69-658e08262082/comments HTTP/1.1
Content-Type: application/json

{
  "message": "Bla bla bla bla",
  "userId": "76d686f6-28b3-484c-ad03-353a76643115"
}

###
