# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.com",
  "dateBirth": "2012-02-22",
  "avatarUrl": "http://photo1.jpg",
  "username": "TestName",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/76d686f6-28b3-484c-ad03-353a76643115 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

###

# Change user password
PUT http://localhost:3000/api/auth/ab1c1a80-a992-4713-9521-8b31e497972c/password HTTP/1.1
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "654321"
}

###
